name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Restore tools
        run: dotnet tool restore

      - name: Check code format
        run: dotnet fantomas --check .

      - name: Test for HC stable
        run: dotnet test -c Release -maxCpuCount

      - name: Test for HC prerelease
        run: dotnet test -c Release_HCPre -maxCpuCount

      - name: Pack for HC stable
        run: dotnet pack -c Release src/FSharp.HotChocolate/FSharp.HotChocolate.fsproj

      - name: Pack for HC prerelease
        run: dotnet pack -c Release_HCPre src/FSharp.HotChocolate/FSharp.HotChocolate.fsproj

      - name: Push
        if: startsWith(github.ref, 'refs/tags/v/')
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push "**/*.nupkg" -s "https://api.nuget.org/v3/index.json" -k "$NUGET_API_KEY" --skip-duplicate
